### PR TITLE
Fix Icons

### PR DESCRIPTION
**Pull request by pizza2004**
The icons were incorrectly linked to files that did not exist in the repository.

### CODE REVIEW

**Comment by LRFLEW** [comment]
a) My .gitignore addition meant that the icon files weren't added
b) This is still wrong. Look at the project itself. Going OpenRCT2 -> OpenRCT2 (Targets) -> Build Phases -> Setup AppIcon, you will see the script that performs the hard links necessary to get the AppIcon to work correctly. I am not adding the files to the repository on purpose, as there's no reason to duplicate the files. Just try building the project, and it should work.

**Comment by pizza2004** [comment]
It doesn't work, because unless the files are on the repository in that directory it can't find them, and gives me 10 warnings instead, but you're right, this commit didn't fix the issue, it just moved the files into the same place you had them again, which is why it appeared to work for me.  I'm looking into a solution.

**Comment by LRFLEW** [comment]
> It doesn't work, because unless the files are on the repository in that directory it can't find them

That's why the script copies them. As soon as you start building it, the script copies the image files to where they are needed, so it shouldn't complain. What's the content of the warnings? If you replace all the instances of `ln` with `cp` in the script does it work?

**Comment by pizza2004** [comment]
Ah, I figured it out.  For some reason it just wasn't running your setup portion when it couldn't download the library.  I stuck the library on my own server and just modified the script to download it from there to try it and it got the icons and everything properly.  I'll close this then!

**Pull request closed without merging**
